### ISSUE TITLE
runtime exits before rust function can be called

### ISSUE THREAD

**Issue by superchris** [ianjsikes/rust-wasm-webpack-tutorial#1]
I get this in the console:  Assertion failed: the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits). This is after I see `Calling rust functions from javascript!` but I do not see the result of calling the function.

**Comment by belfz** [comment]
I get the same error. After some research, it looks like some missing compiler flag. Any ideas on how to fix that?

**Comment by superchris** [comment]
Yes, I this is fixed in PR #2 it just hasn't been merged.

**Comment by superchris** [comment]
Oops i shouldn't have closed it yet

**Comment by marcocastignoli** [comment]
You forgot to update {noExitRuntime: true} on https://medium.com/@ianjsikes/get-started-with-rust-webassembly-and-webpack-58d28e219635

**Comment by ianjsikes** [comment]
Got it, thanks for the reminder.
